### ISSUE TITLE
Принимается!

### ISSUE THREAD

**Issue by phoenixweiss** [MeldyTheCoder/homework_1#1]
Понятно 😄 
https://github.com/MeldyTheCoder/homework_1/blob/6bfd3298494b7a3a9a201586ffe80e347d2aa517/script.js#L5

Адекватно:
https://github.com/MeldyTheCoder/homework_1/blob/6bfd3298494b7a3a9a201586ffe80e347d2aa517/script.js#L7-L8

Неплохо придумал:
https://github.com/MeldyTheCoder/homework_1/blob/6bfd3298494b7a3a9a201586ffe80e347d2aa517/script.js#L13-L17

Условия верные:
https://github.com/MeldyTheCoder/homework_1/blob/6bfd3298494b7a3a9a201586ffe80e347d2aa517/script.js#L19-L28

Молодец. Можешь гордо закрыть данный Issue.

**Comment by MeldyTheCoder** [comment]
😎
